version: '3.7'
services:
 todo-app:
   image: todo-crud
   container_name: todo-app
   ports:
    - "8080:8080"
   depends_on:
    - "dynamodb-local"
   links:
    - "dynamodb-local"
   environment:
    - AWS_ACCESS_KEY_ID=process.env.ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=process.env.SECRET_ACCESS_KEY
    - REGION='us-west-1'
 dynamodb-local:
   image: amazon/dynamodb-local:latest
   container_name: dynamodb-local
   ports:
    - "8000:8000"